# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
# molokai
# onedark
# jellybeans
# palenight
# nord
# material

colorscheme = 'SpaceVim'
colorscheme_bg = 'dark'
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true

# Disable statusline separator, if you want to use other value, please
# install nerd fonts
# statusline_separator = 'arrow'
statusline_separator = 'arrow'

# tabline
enable_tabline_filetype_icon = true
# Enable/Disable show mode on statusline
enable_statusline_mode = true

# Set SpaceVim buffer index type
buffer_index_type = 4
# 0: 1 ➛ ➊
# 1: 1 ➛ ➀
# 2: 1 ➛ ⓵
# 3: 1 ➛ ¹
# 4: 1 ➛ 1

# left sections of statusline
statusline_left_sections = [
    'winnr',
    'major mode',
    'filename',
    'fileformat',
    'minor mode lighters',
    'version control info',
    'search status'
]
# right sections of statusline
statusline_right_sections = [
    'cursorpos',
    'percentage',
    'input method',
    'date',
    'time'
]

# 'winnr' window number
# 'syntax checking'
# 'filename' file name
# 'fileformat' file format
# 'major mode'
# 'minor mode lighters'
# 'cursorpos' cursor position
# 'percentage' content range
# 'date' date
# 'time' time
# 'whitespace' line number with trailing space at the end
# 'battery status' battery status
# 'input method' input method
# 'search status' search index

# font
guifont = 'SourceCodePro Nerd Font Mono:h13'

# indent
default_indent = 4
expand_tab = true

# project manage
project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/', '!node_packages/']
project_rooter_outermost = false

# file manager plugins supported in SpaceVim:
# - vimfiler (default)
# - nerdtree
# - defx
filemanager = 'nerdtree'
enable_vimfiler_gitstatus = true

# ycm: for YouCompleteMe
# neocomplcache
# coc: coc.nvim which also provides language server protocol feature
# deoplete
# asyncomplete
# completor
autocomplete_method = 'deoplete'
snippet_engine = 'ultisnips'
#enable_ycm = true

# lint
#lint_engine = 'ale'
#lint_engine = 'neomake'

# bootstrap function
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = 'complete'
  auto-completion-tab-key-behavior = 'smart'

[[layers]]
  name = 'shell'
  default_position = 'right'
  #default_position = 'buttom'
  #default_height = 30

[[layers]]
  name = 'lang#WebAssembly'

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = 'lang#c'
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    c = 'c11'
    cpp = 'c++1z'
    objc = 'c11'
    objcpp = 'c++1z'

[[layers]]
  name = 'lang#dockerfile'

[[layers]]
  name = 'lang#go'

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#python'
  format_on_save = true
  enabled_linters = ['python', 'flake8']
  python_file_head = [
      '#!/usr/bin/env python',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lang#vim'

[[layers]]
  name = 'lang#toml'

[[layers]]
  name = 'lang#lua'

[[layers]]
  name = 'colorscheme'

[[layers]]
#  name = 'fzf'
name = 'leaderf'

[[layers]]
  name = 'format'

[[layers]]
  name = 'git'

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'go',
    'python',
    'rust'
  ]
  [layers.override_cmd]
    rust = ['rls']
    go = ['go-langserver', '-mode', 'stdio']
    c = ["clangd"]

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'tools#dash'

#[[layers]]
#  name = "tools#zeal"

# core
[[layers]]
  name = 'core'
  filetree_show_hidden = true

[[layers]]
  name = 'core#banner'

[[layers]]
  name = 'core#tabline'

# ale
# neomake
# syntastic
[[layers]]
  name = 'checker'
  lint_on_the_fly = false
  lint_on_save = true
  show_cursor_error	= true

[[layers]]
  name = "incsearch"

[[layers]]
  name = "ctrlspace"

# [[layers]]
#    name = "debug"

# [[layers]]
#   name = "tags"

# [[layers]]
#   name = "gtags"
#   gtagslabel = "ctags"

# [[custom_plugins]]
#     name = "Shougo/deoplete.nvim"
#     merged = false

# [[custom_plugins]]
#     name = "tbodt/deoplete-tabnine"
#     merged = false

# [[custom_plugins]]
#     name = "vim-python/python-syntax"
#     merged = false

# [[custom_plugins]]
#     name = "sebdah/vim-delve"

