# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
#colorscheme = "gruvbox"
#colorscheme = "desert"
#colorscheme = "onedark"
#colorscheme = "molokai"
#colorscheme = "material"
colorscheme = "SpaceVim"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
#guifont = "SauceCodePro Nerd Font Mono:h11"
#guifont = "Source Code Pro:h14"
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false

# file manager plugins supported in SpaceVim:
# - vimfiler (default)
# - nerdtree
# - defx
filemanager = "defx"
enable_vimfiler_gitstatus = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#WebAssembly"

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
[layer.clang_std]
c = "c11"
cpp = "c++1z"
objc = "c11"
objcpp = "c++1z"

[[layers]]
name = "lang#clojure"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#elixir"

[[layers]]
name = "lang#erlang"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#plantuml"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#vim"

[[layers]]
name = "tools#zeal"

[[layers]]
name = "tools#dash"

[[layers]]
name = "colorscheme"

[[layers]]
name = "fzf"
